FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN apk add --no-cache curl

# Nginx config will be mounted as a volume
# Static files will be mounted as volumes for development

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]